name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  smoke:
    name: Smoke Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Restore history (if exists)
      - name: Download Allure History (Regression)
        uses: actions/download-artifact@v4
        with:
          name: allure-history-regression
          path: allure-results/history
        continue-on-error: true

      - name: Run smoke tests
        run: npx playwright test --grep @smoke

      # Generate Allure HTML report for smoke
      - name: Generate Allure Report (Smoke)
        if: always()
        run: npx allure generate allure-results --clean -o allure-report-smoke

      # Save smoke history
      - name: Upload Allure History (Smoke)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-history-smoke
          path: allure-report-smoke/history

      # Upload raw Allure results
      - name: Upload Allure Results (Smoke)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-smoke
          path: allure-results

      # Upload HTML Allure report
      - name: Upload Allure Report (Smoke)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-smoke
          path: allure-report-smoke

  regression:
    name: Regression Tests
    runs-on: ubuntu-latest
    needs: smoke